name: ci-sonarcloud
on: 
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.0-rc1'
      - run: go test -covereprofile=coverage.out